import React from 'react';
import { Link } from 'react-router-dom';
import { Activity, Brain, Utensils, LineChart, Zap } from 'lucide-react';
import AdvisoryBanner from '../components/AdvisoryBanner';

const Landing: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-950 flex flex-col">
      {/* Hero Section */}
      <div className="relative overflow-hidden pt-20 pb-32 lg:pt-32 lg:pb-40">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-emerald-500/20 rounded-full blur-[120px] -z-10 pointer-events-none"></div>
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gray-900 border border-gray-800 text-emerald-400 text-sm font-medium mb-8">
            <Activity className="h-4 w-4" />
            <span>Vitalis AI is now in Beta</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-extrabold text-white tracking-tight mb-8">
            Your AI-Powered <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-500">
              Personal Trainer & Nutritionist
            </span>
          </h1>
          
          <p className="max-w-2xl mx-auto text-xl text-gray-400 mb-10">
            Hyper-personalized workout and meal plans generated by advanced AI, tailored to your unique body, goals, and lifestyle.
          </p>
          
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Link to="/register" className="bg-gradient-to-r from-emerald-500 to-cyan-600 text-white px-8 py-4 rounded-xl font-bold text-lg hover:opacity-90 transition shadow-[0_0_30px_rgba(16,185,129,0.3)]">
              Get Started Free
            </Link>
            <Link to="/login" className="bg-gray-900 border border-gray-800 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-gray-800 transition">
              Sign In
            </Link>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="py-20 bg-gray-900/50 border-y border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4">Smarter Fitness, Better Results</h2>
            <p className="text-gray-400">Everything you need to reach your goals, powered by artificial intelligence.</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="bg-gray-900 p-8 rounded-2xl border border-gray-800 hover:border-emerald-500/50 transition duration-300">
              <div className="bg-emerald-500/10 w-14 h-14 rounded-xl flex items-center justify-center mb-6">
                <Brain className="h-7 w-7 text-emerald-500" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">AI-Powered Plans</h3>
              <p className="text-gray-400">Algorithms that understand your body type, goals, and experience level to create the perfect routine.</p>
            </div>
            
            <div className="bg-gray-900 p-8 rounded-2xl border border-gray-800 hover:border-cyan-500/50 transition duration-300">
              <div className="bg-cyan-500/10 w-14 h-14 rounded-xl flex items-center justify-center mb-6">
                <Utensils className="h-7 w-7 text-cyan-500" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Personalized Nutrition</h3>
              <p className="text-gray-400">Exact macros and daily meal suggestions that fit your dietary preferences and restrictions.</p>
            </div>
            
            <div className="bg-gray-900 p-8 rounded-2xl border border-gray-800 hover:border-emerald-500/50 transition duration-300">
              <div className="bg-emerald-500/10 w-14 h-14 rounded-xl flex items-center justify-center mb-6">
                <LineChart className="h-7 w-7 text-emerald-500" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Progress Tracking</h3>
              <p className="text-gray-400">Log your weight and let the AI adjust your plan dynamically based on your actual results.</p>
            </div>
            
            <div className="bg-gray-900 p-8 rounded-2xl border border-gray-800 hover:border-cyan-500/50 transition duration-300">
              <div className="bg-cyan-500/10 w-14 h-14 rounded-xl flex items-center justify-center mb-6">
                <Zap className="h-7 w-7 text-cyan-500" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Adaptive Programs</h3>
              <p className="text-gray-400">As you grow stronger and your needs change, your program evolves with you automatically.</p>
            </div>
          </div>
        </div>
      </div>

      {/* How it Works */}
      <div className="py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4">How It Works</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 relative">
            <div className="hidden md:block absolute top-12 left-1/6 right-1/6 h-0.5 bg-gradient-to-r from-emerald-500/0 via-emerald-500/50 to-cyan-500/0 z-0"></div>
            
            <div className="relative z-10 text-center">
              <div className="w-24 h-24 mx-auto bg-gray-900 border-2 border-emerald-500 rounded-full flex items-center justify-center text-2xl font-bold text-white mb-6 shadow-[0_0_20px_rgba(16,185,129,0.2)]">1</div>
              <h3 className="text-xl font-bold text-white mb-3">Create Profile</h3>
              <p className="text-gray-400">Tell us about your body, goals, equipment, and dietary needs in a quick 2-minute onboarding.</p>
            </div>
            
            <div className="relative z-10 text-center">
              <div className="w-24 h-24 mx-auto bg-gray-900 border-2 border-emerald-500 rounded-full flex items-center justify-center text-2xl font-bold text-white mb-6 shadow-[0_0_20px_rgba(16,185,129,0.2)]">2</div>
              <h3 className="text-xl font-bold text-white mb-3">Get Your Plan</h3>
              <p className="text-gray-400">Our AI generates a comprehensive 7-day workout schedule and complete nutritional guide.</p>
            </div>
            
            <div className="relative z-10 text-center">
              <div className="w-24 h-24 mx-auto bg-gray-900 border-2 border-cyan-500 rounded-full flex items-center justify-center text-2xl font-bold text-white mb-6 shadow-[0_0_20px_rgba(6,182,212,0.2)]">3</div>
              <h3 className="text-xl font-bold text-white mb-3">Track & Adapt</h3>
              <p className="text-gray-400">Log your progress and regenerate your plan anytime to keep pushing towards your goals.</p>
            </div>
          </div>
        </div>
      </div>

      <AdvisoryBanner />
    </div>
  );
};

export default Landing;
